// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcEMlokh__6oJf8kb4ecTX5HA2NYRaNG8',
    appId: '1:162784190733:web:672472e741cb51229ad044',
    messagingSenderId: '162784190733',
    projectId: 'talky-c-690',
    authDomain: 'talky-c-690.firebaseapp.com',
    storageBucket: 'talky-c-690.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm4EK9jj2kK_8ELvmVYYM2VLrK2dYsvEY',
    appId: '1:162784190733:android:5705883eb7850b8f9ad044',
    messagingSenderId: '162784190733',
    projectId: 'talky-c-690',
    storageBucket: 'talky-c-690.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA--YGYjtfXttQUE71jX_cZ-vk_LEk-xZQ',
    appId: '1:162784190733:ios:5dfe7b1cebbab4259ad044',
    messagingSenderId: '162784190733',
    projectId: 'talky-c-690',
    storageBucket: 'talky-c-690.appspot.com',
    iosBundleId: 'com.example.talky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA--YGYjtfXttQUE71jX_cZ-vk_LEk-xZQ',
    appId: '1:162784190733:ios:0009e319e511c4c49ad044',
    messagingSenderId: '162784190733',
    projectId: 'talky-c-690',
    storageBucket: 'talky-c-690.appspot.com',
    iosBundleId: 'com.example.talky.RunnerTests',
  );
}
